-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

hl.config({}) -- remove this line to remove the warning

-- Global Programs Configuration
terminal    = "kitty"
fileManager = "dolphin"
menu        = "hyprlauncher"

-- Require config components
require("environment")
require("monitors")
require("input")
require("appearance")
require("animations")
require("rules")
require("keybinds")
require("autostart")
